### ISSUE TITLE
Error undefined method `jd' for

### ISSUE THREAD

**Issue by glafir** [varvet/sun_time#5]
undefined method `jd' for Wed, 19 Apr 2017 02:13:01 YAKT +09:00:Time

sr = sun_time.sunrise.in_time_zone(@airport.time_zone).to_s(:time) if sun_time.sunrise != nil

rails 5.0.2
Ruby 2.3 0

**Comment by cjse** [comment]
Hi @glafir, could you include a stack trace?

**Comment by glafir** [comment]
```
Trace of template inclusion: app/views/airports/show.html.haml

Rails.root: /home/glafir/RoR/ic-glafir
Application Trace | Framework Trace | Full Trace

activesupport (5.0.2) lib/active_support/time_with_zone.rb:462:in `method_missing'
sun_time (0.0.2) lib/sun_time.rb:38:in `j_date'
sun_time (0.0.2) lib/sun_time.rb:58:in `n'
sun_time (0.0.2) lib/sun_time.rb:110:in `j_star'
sun_time (0.0.2) lib/sun_time.rb:52:in `m'
sun_time (0.0.2) lib/sun_time.rb:94:in `j_transit'
sun_time (0.0.2) lib/sun_time.rb:115:in `j_rise'
sun_time (0.0.2) lib/sun_time.rb:22:in `sunrise'
app/views/airports/_info.html.haml:32:in `_app_views_airports__info_html_haml___1429558860626825617_75831780'
actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.2) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.2) lib/action_view/template.rb:157:in `render'
actionview (5.0.2) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
actionview (5.0.2) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.2) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.0.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.0.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
haml (4.0.7) lib/haml/helpers.rb:89:in `non_haml'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
app/views/airports/show.html.haml:10:in `_app_views_airports_show_html_haml___4160361206338409863_80331000'
actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.2) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.2) lib/action_view/template.rb:157:in `render'
actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.2) lib/action_view/rendering.rb:104:in `_render_template'
actionpack (5.0.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.2) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/glafir/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (2.3.0) lib/action_controller/responder.rb:238:in `default_render'
responders (2.3.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.3.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.3.0) lib/action_controller/responder.rb:156:in `call'
responders (2.3.0) lib/action_controller/respond_with.rb:205:in `respond_with'
app/controllers/airports_controller.rb:62:in `show'
actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
react-rails (2.0.2) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (5.0.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:285:in `block in halting'
activesupport (5.0.2) lib/active_support/callbacks.rb:447:in `block in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
rack-mobile-detect (0.4.0) lib/rack/mobile-detect.rb:164:in `call'
rack-attack (5.0.1) lib/rack/attack.rb:147:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
rack-attack (5.0.1) lib/rack/attack.rb:147:in `call'
rack (2.0.1) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.1) lib/rack/lint.rb:49:in `_call'
rack (2.0.1) lib/rack/lint.rb:37:in `call'
rack (2.0.1) lib/rack/show_exceptions.rb:23:in `call'
rack (2.0.1) lib/rack/common_logger.rb:33:in `call'
rack (2.0.1) lib/rack/chunked.rb:54:in `call'
rack (2.0.1) lib/rack/content_length.rb:15:in `call'
unicorn (5.3.0) lib/unicorn/http_server.rb:606:in `process_client'
unicorn (5.3.0) lib/unicorn/http_server.rb:702:in `worker_loop'
unicorn (5.3.0) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
unicorn (5.3.0) lib/unicorn/http_server.rb:142:in `start'
unicorn (5.3.0) bin/unicorn:126:in `<top (required)>'
/home/glafir/.rvm/gems/ruby-2.3.0/bin/unicorn:23:in `load'
/home/glafir/.rvm/gems/ruby-2.3.0/bin/unicorn:23:in `<main>'
/home/glafir/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/glafir/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by glafir** [comment]
Yes, I find it!
in sun_time.rb library in action

  # Julian date
  def j_date
    date.jd
  end

I rewrite this.
  # Julian date
  def j_date
    date.to_datetime.jd
  end

Its work!

**Comment by glafir** [comment]
Because "DateTime.current.in_time_zone" return type Time no DateTime.
